# Generated by Django 5.1.2 on 2024-10-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projCadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
