# Generated by Django 5.1.3 on 2024-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_descricao', models.CharField(max_length=100)),
                ('tar_setor', models.CharField(max_length=100)),
                ('tar_prioridade', models.CharField(max_length=100)),
                ('tar_status', models.CharField(max_length=100)),
                ('tar_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nome', models.CharField(max_length=40)),
                ('usu_email', models.CharField(max_length=30)),
            ],
        ),
    ]
