# Generated by Django 5.1.3 on 2024-11-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetotask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_usuario',
            new_name='tbl_usuarios',
        ),
    ]
